### GET all cocheras
http://localhost:3000/api/garages


### POST a Cochera
# @name createGarage
POST http://localhost:3000/api/garages
Content-Type: application/json


{
    "cuit": 123456,
    "name": "CocheraSanjorge",
    "address": "españa 123",
    "password": "test",
    "phoneNumber": "444525",
    "email": "cochera@gmail.com",
    "location": 1,
    "parkingSpace": [] ,
    "reservation": [] ,
    "reservationType": []  
}


### Cuit es primary key
@cuit = {{createGarage.response.body.cuit}}


### GET ONE 
http://localhost:3000/api/garages/{{cuit}}


### PUT
PUT  http://localhost:3000/api/garages/{{cuit}}
Content-Type: application/json

{
    "cuit": 888,
    "name": "CocheraSur",
    "address": "Colon 2400",
    "phoneNumber": "577735851",
    "email": "cocherSur@gmail.com",
    "location": 1,
    "parkingSpace": []  
}


### POST Cochera TO DELETE
# @name createGarageToDelete
POST http://localhost:3000/api/garages
Content-Type: application/json

{
    "cuit": 7777,
    "name": "CocheraCentro",
    "address": "Dorrego 1400",
    "phoneNumber": "54235851",
    "email": "cocherC@gmail.com",
    "location": 1,
    "parkingSpace": []  
}

### CUIT
@cuitToDelete = {{createGarageToDelete.response.body.cuit}}

### DELETE
DELETE http://localhost:3000/api/garages/{{cuitToDelete}}

### GET availables garages
GET http://localhost:3000/api/garages/availables?check_in_at=2024-12-20%2015:30&check_out_at=2024-12-20%2016:30&license_plate=123456
