### GET all cocheras
http://localhost:3000/api/garages


### POST a Cochera
# @name createGarage
POST http://localhost:3000/api/garages
Content-Type: application/json


{
    "cuit": 666626,
    "name": "CocherRosario",
    "address": "Dorrego 123",
    "phone_number": "444689525",
    "email": "cocherRosario@gmail.com",
    "priceHour": 555,
    "location": 1,
    "parkingSpace": []  
}


### Cuit es primary key
@cuit = {{createGarage.response.body.cuit}}


### GET ONE 
http://localhost:3000/api/garages/{{cuit}}


### PUT
PUT  http://localhost:3000/api/garages/{{cuit}}
Content-Type: application/json

{
    "cuit": 888,
    "name": "CocheraSur",
    "address": "Colon 2400",
    "phone_number": "577735851",
    "email": "cocherSur@gmail.com",
    "priceHour": 200,
    "location": 1,
    "parkingSpace": []  
}


### POST Cochera TO DELETE
# @name createGarageToDelete
POST http://localhost:3000/api/garages
Content-Type: application/json

{
    "cuit": 7777,
    "name": "CocheraCentro",
    "address": "Dorrego 1400",
    "phone_number": "54235851",
    "email": "cocherC@gmail.com",
    "priceHour": 100,
    "location": 1,
    "parkingSpace": []  
}

### CUIT
@cuitToDelete = {{createGarageToDelete.response.body.cuit}}

### DELETE
DELETE http://localhost:3000/api/garages/{{cuitToDelete}}
