### obtener todas las localidades
http://localhost:3000/api/locations


### create a localidad
# @name createLocation
POST http://localhost:3000/api/locations
Content-Type: application/json

{
    "name": "San Vicente",
    "province": "Santa Fe",
    "garage": []  
}

###ID
@id = {{createLocation.response.body.data.id}}

### GET ONE 
http://localhost:3000/api/locations/{{id}}


### PUT
PUT  http://localhost:3000/api/locations/{{id}}
Content-Type: application/json

{
    "name": "Rosario",
    "province": "Santa Fe",
    "garage": []  
}


### POST LOCALIDAD TO DELETE
# @name createLocationToDelete
POST http://localhost:3000/api/locations
Content-Type: application/json

{
    "name": "San Francisco",
    "province": "Cordoba",
    "garage": []  
}


### DELETE
@idToDelete = {{createLocationToDelete.response.body.data.id}}
DELETE http://localhost:3000/api/locations/{{idToDelete}}