### GET all parking_space
http://localhost:3000/api/parkingSpaces


### POST a parking_space
POST http://localhost:3000/api/parkingSpaces
Content-Type: application/json


{
    "number": 6,
    "garage": 888,
    "TypeVehicle": 1
}


### GET ONE parking_space
http://localhost:3000/api/parkingSpaces/1


### PUT parking_space
PUT  http://localhost:3000/api/parkingSpaces/3/888
Content-Type: application/json

{
    "TypeVehicle": 2 
}


###
POST http://localhost:3000/api/parkingSpaces
Content-Type: application/json

{
    "number": 7777,
    "garage": 888
}


### DELETE parking_space
DELETE http://localhost:3000/api/parkingSpaces/
