### GET all parking_space
http://localhost:3000/api/parkingSpaces


### POST a parking_space
# @name createParking_space
POST http://localhost:3000/api/parkingSpaces
Content-Type: application/json


{
    "number": 1,
    "garage": 888
}


### Number es primary key
@number = {{createParking_space.response.body.number}}


### GET ONE parking_space
http://localhost:3000/api/parkingSpaces/1


### PUT parking_space
PUT  http://localhost:3000/api/parkingSpaces/1
Content-Type: application/json

{
    "number": 8,
    "garage": 888
}


### POST parking_space TO DELETE
# @name createGarageToDelete
POST http://localhost:3000/api/parkingSpaces
Content-Type: application/json

{
    "number": 7777,
    "garage": 888
}

### CUIT
@numberToDelete = {{createGarageToDelete.response.body.number}}

### DELETE parking_space
DELETE http://localhost:3000/api/parkingSpaces/{{numberToDelete}}
