### obtener todos los tipos de estadía
GET http://localhost:3000/api/reservationTypes


### obtener un solo tipo de estadía
GET http://localhost:3000/api/reservationTypes/


### crear un nuevo tipo de estadía
# @name createReservationType
POST http://localhost:3000/api/reservationTypes
Content-Type: application/json

{
    "description": "HOUR",
    "garage": 888,
    "price": 1000
    
}


### modificar un tipo de estadía 
PUT http://localhost:3000/api/reservationTypes/HOUR/888
Content-Type: application/json

{
    "price": 2000
}


### crear un tipo de estadía TO DELETE
# @name createReservationTypeToDelete
POST http://localhost:3000/api/reservationTypes
Content-Type: application/json

{
    "description": "quincena",
    "price": 1000
}


### crear un tipo de estadía
DELETE http://localhost:3000/api/reservationTypes/HOUR/888