### obtener todas las reservas
GET http://localhost:3000/api/reservations


### obtener una reserva
GET http://localhost:3000/api/reservations/{{id}}


### crear una nueva reserva
# @name createReservation
POST http://localhost:3000/api/reservations
Content-Type: application/json

{
    "check_in_at": "2024-10-15T15:30",
    "check_out_at": "2024-10-15T17:00",
    "license_plate": "123456",
    "cuitGarage": 888
}

###ID
@id = {{createReservation.response.body.id}}


### modificar una reserva
PUT http://localhost:3000/api/reservations/{{id}}
Content-Type: application/json

{

}


### eliminar una reserva
DELETE http://localhost:3000/api/reservations/{{id}}