### obtener todos los tipos de estadía
GET http://localhost:3000/api/tiposE


### obtener un solo tipo de estadía
GET http://localhost:3000/api/tiposE/{{tipoE}}


### crear un nuevo tipo de estadía
# @name createTipoEstadia
POST http://localhost:3000/api/tiposE
Content-Type: application/json

{
    "tipoE": "mensual"
}

###Primarykey
@tipoE = {{createTipoEstadia.response.body.data.tipoE}}

### modificar un tipo de estadía 
PUT http://localhost:3000/api/tiposE/{{tipoE}}
Content-Type: application/json

{
    "tipoE": "diario"
}


### crear un tipo de estadía TO DELETE
# @name createTipoEstadiaToDelete
POST http://localhost:3000/api/tiposE
Content-Type: application/json

{
    "tipoE": "quincena"
}


###Primarykey
@tipoEToDelete = {{createTipoEstadiaToDelete.response.body.data.tipoE}}


### crear un tipo de estadía
DELETE http://localhost:3000/api/tiposE/{{tipoEToDelete}}