
### obtener todos los vehículos
GET http://localhost:3000/api/vehicles


### obtener un solo vehículo
GET http://localhost:3000/api/vehicles/{{license_plate}}


### crear un nuevo vehículo
# @name createVehiculo
POST http://localhost:3000/api/vehicles
Content-Type: application/json

{
    "license_plate": "123456",
    "owner": 1,
    "type": 2
}

###ID
@license_plate = {{createVehiculo.response.body.data.license_plate}}

### modificar un vehículo
PUT http://localhost:3000/api/vehicles/{{license_plate}}
Content-Type: application/json

{
    "license_plate": "dddd"
}


### crear un vehiculo TO DELETE
# @name createVehiculoToDelete
POST http://localhost:3000/api/vehicles
Content-Type: application/json

{
    "license_plate": "1111",
    "owner": 3
}


### Patente
@license_plateToDelete = {{createVehiculoToDelete.response.body.data.license_plate}}

### eliminar un vehículo
DELETE http://localhost:3000/api/vehicles/{{license_plateToDelete}}