
### obtener todos los usuarios
GET http://localhost:3000/api/users


### obtener un usuario
GET http://localhost:3000/api/users/{{id}}


### crear un nuevo usuario
# @name createManuel
POST http://localhost:3000/api/users
Content-Type: application/json


{
    "name": "Juan",
    "lastname": "Perez",
    "dni": "12345678",
    "address": "Dorrego 700",
    "mail": "manuvariego@gmail.com",
    "telephone": "3416538852",
    "vehiculo": []
}
###ID
@id = {{createManuel.response.body.data.id}}

### modificar un usuario
PUT http://localhost:3000/api/users/{{id}}
Content-Type: application/json

{
    "name": "Candela",
    "lastname": "Tanchi",
    "dni": "45656415",
    "address": "España 1800",
    "mail": "candetanchi@gmail.com",
    "telephone": "3413654987",
    "vehiculo": []
}


### eliminar un usuario
DELETE http://localhost:3000/api/users/{{id}}
