
### obtener todos los usuarios
GET http://localhost:3000/api/users


### obtener un usuario
GET http://localhost:3000/api/users/8b2dd650-d0b4-49b9-b2b4-113f25a3fa06


### crear un nuevo usuario
POST  http://localhost:3000/api/users/
Content-Type: application/json

{
    "name": "Manuel",
    "lastname": "Variego",
    "dni": "12345678",
    "address": "Dorrego 700",
    "mail": "manuvariego@gmail.com",
    "telephone": 3416538852
}


### modificar un usuario
PUT http://localhost:3000/api/users/8b2dd650-d0b4-49b9-b2b4-113f25a3fa06
Content-Type: application/json

{
    "name": "Candela",
    "lastname": "Tanchi",
    "dni": "45656415",
    "address": "España 1800",
    "mail": "candetanchi@gmail.com",
    "telephone": 3413654987
}


### eliminar un usuario
DELETE http://localhost:3000/api/users/8b2dd650-d0b4-49b9-b2b4-113f25a3fa06
